####################################################
## PANAMA: Services Architecture Definition ##
####################################################

glance:
  ports: 
    - 9292
    - 4324
  volumes: 
    '/var/log/supervisor': '/var/log/panama/glance'
    '/etc/glance': '/var/lib/panama/glance/etc'
  privileged: false


horizon:
  ports:
    - 80
    - 11211 
  volumes:
    '/var/log/supervisor': '/var/log/panama/horizon'
    '/etc/openstack-dashboard': '/var/lib/panama/horizon/etc'
  privileged: false


keystone:
  ports:
    - 35357
    - 5000
  volumes:
    '/var/log/supervisor': '/var/log/panama/keystone'
    '/etc/keystone': '/var/lib/panama/keystone/etc'
  privileged: false


mysql:
  ports:
    - 3306
  volumes:
    '/var/log/supervisor': '/var/log/panama/mysql'
  privileged: false


nova:
  ports:
    - 8774
    - 8775
  volumes:
    '/var/log/supervisor': '/var/log/panama/nova'
    '/etc/nova': '/var/lib/panama/nova/etc'
  privileged: true


rabbitmq:
  ports:
    - 5672
    - 15672
  volumes:
    '/var/log/supervisor': '/var/log/panama/rabbitmq'
    '/etc/rabbitmq': '/var/lib/panama/rabbitmq/etc'
  privileged: false

