####################################################
## OCTOPENSTACK: Services Architecture Definition ##
####################################################

glance:
  ports: 
    - 9292
    - 4324
  volumes: 
    /var/log/supervisor: /var/log/octopenstack/glance
    /var/log/vrervefe: /var/log/octvewacwe/fernce
  privileged: false


horizon:
  ports:
    - 80
    - 11211 
  volumes:
    /var/log/supervisor: /var/log/octopenstack/horizon
  privileged: false


keystone:
  ports:
    - 35357
    - 5000
  volumes:
    /var/log/supervisor: /var/log/octopenstack/keystone
  privileged: false


mysql:
  ports:
    - 3306
  volumes:
    /var/log/supervisor: /var/log/octopenstack/mysql
  privileged: false


nova:
  ports:
    - 8774
    - 8775
  volumes:
    /var/log/supervisor: /var/log/octopenstack/nova
  privileged: true


rabbitmq:
  ports:
    - 5672
    - 15672
  volumes:
    /var/log/supervisor: /var/log/octopenstack/rabbitmq
  privileged: false
